### ISSUE TITLE
小米手机上调用mediaplayer无法播放视频

### ISSUE THREAD

**Issue by metaxapp** [JeffMony/MediaSDK#5]
ijk和exo都能正常缓存后播放，只有内置的mediaplayer不行，不知道是什么原因。（已测试4.4、7.1、8.0系统，mp4和hls视频都不行）

**Comment by JeffMony** [comment]
> ijk和exo都能正常缓存后播放，只有内置的mediaplayer不行，不知道是什么原因。（已测试4.4、7.1、8.0系统，mp4和hls视频都不行）

手头没有小米手机，可以告知具体的错误吗？

**Comment by metaxapp** [comment]
> > ijk和exo都能正常缓存后播放，只有内置的mediaplayer不行，不知道是什么原因。（已测试4.4、7.1、8.0系统，mp4和hls视频都不行）
> 
> 手头没有小米手机，可以告知具体的错误吗？
找到原因了，mediaplayer只支持整型的#EXT-X-TARGETDURATION。
另外发现一个问题，就是LocalProxyServer里面没有缓存直接下载资源时，inputstream流在保存文件时读取一次后，不能够直接返回inputstream供播放器使用，目前我是保存后再返回一个new FileInputStream(file)。可能exo等播放器有获取失败后自动重连的机制（第二次自动读取了缓存），所以你没发现这个错误

**Comment by JeffMony** [comment]
很有见地，可以一起维护这个项目。

**Comment by metaxapp** [comment]
不过这个方案只能解决hls的问题，mp4流我还不知道怎么解决
